# Generated by Django 5.0.2 on 2024-03-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Quest_Config', '0002_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
