# Generated by Django 5.0.2 on 2024-03-13 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Quest_Config', '0003_remove_task_email_remove_task_password'),
        ('Task_Quest_Config', '0005_profile'),
    ]

    operations = [
    ]
